### ISSUE TITLE
Telegraf. Docker metrics are not Ingested by openobserve

### ISSUE THREAD

**Issue by userdeveloper98** [openobserve/openobserve#1437] opened 2023-08-28 15:46 UTC
### Which OpenObserve functionalities are the source of the bug?

streams, ingestion, metrics

### Is this a regression?

Yes

### Description

Docker metrics (**[[inputs.docker]]**)  are not ingested by openobserve.
All metrics are shown in "Streams" and "Metrics" but nothing related to docker.
The same telegraf config/setup works when pointed to influxdb

Steps to reproduce:

**Telegraf docker-compose file:**
```

version: '2.1'

services:
  telegraf:
    image: telegraf:1.19.1
    container_name: telegraf
    privileged: true
    cpuset: 1,2,3
    cpu_shares: 256
    mem_reservation: 100m
    mem_limit: 200m
    restart: unless-stopped
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/hostfs/var/run/docker.sock:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
```

./telegraf.conf file:
```

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  omit_hostname = false

[[outputs.file]]
  files = ["stdout"]

[[outputs.http]]
  ## URL is the address to send metrics to
  url = "http://192.168.100.100:5080/api/default/prometheus/api/v1/write"
  ## Data format to output.
  data_format = "prometheusremotewrite"

  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
     X-Prometheus-Remote-Write-Version = "0.1.0"
     Authorization = "Basic ********"

[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.system]]
[[inputs.net]]
[[inputs.swap]]
[[inputs.exec]]
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false

[[inputs.docker]]
  endpoint = "unix:///hostfs/var/run/docker.sock"
  container_names = []
  timeout = "10s"
  perdevice = true
  total = false
```

### Please provide a link to a minimal reproduction of the bug

See config files above

### Please provide the exception or error you saw

```true
No errors.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.5.2
Commit Hash: 7c95c24c9d8a6427eb833557897d7fabfc54012b
Build Date: 2023-08-22T11:10:24Z
```

### Anything else?

Logs from telegraf about pushing container metrics (docker_container_cpu in this case):
```
{
_timestamp:1693237003118287,
container_created_at:2023-08-28T15:09:38.925062285Z,
container_id:0b316139e6c4d44d7db3f9f63528d1db946eadf663a7e560a03dd9f9d4c88d18,
container_name:telegraf,
host:8e7fc1b4b7e3,
image:telegraf_telegraf,
label_com_docker_compose_config_hash:e37656e822b464a5e9bfaf273f0a58ecc0ea6c21136227e3dc007125a7051014,
label_com_docker_compose_container_number:1,
label_com_docker_compose_oneoff:False,
label_com_docker_compose_project:telegraf,
label_com_docker_compose_service:telegraf,
label_com_docker_compose_version:1.21.0,
message:docker_container_cpu,com.docker.compose.config-hash=11340039389e6c8c962d52935c5d32bcceaae5593621b2d3b8c6ed1745b65070,com.docker.compose.container-number=1,com.docker.compose.oneoff=False,com.docker.compose.project=portainer_ce,com.docker.compose.service=portainer_ce,com.docker.compose.version=1.21.0,container_image=portainer/portainer-ce,container_name=portainer_ce,container_status=running,container_version=2.0.0-alpine,cpu=cpu3,engine_host=SECRET,host=SECRET,server_version=20.10.17 usage_total=85014786527i,container_id="6a8ad0719460224445ee33f395da81d75ea57b8fd1656004b67ba543cdf1d5c2" 1693236962000000000,
source_type:docker_logs,
stream:stdout,
timestamp:2023-08-28T15:36:42.274261232Z
} 
```

Logs on openobserve side example:
```
{
_timestamp:1693237242635579,
container_created_at:2023-08-27T21:47:13.391409888Z,
container_id:be6b12869f3b8cfc095ddfe1b3415bb425da3465d4cee433fecfdcc9aa2a9cf3,
container_name:openobserve,
host:7ecb7a02942e,
image:public.ecr.aws/zinclabs/openobserve:v0.5.2,
label_com_docker_compose_config_hash:732d098ecfb90887a746aa3c482d8c2645eda2d2c98afc89a5a2fcdbdb657ded,
label_com_docker_compose_container_number:1,
label_com_docker_compose_oneoff:False,
label_com_docker_compose_project:openobserve,
label_com_docker_compose_project_config_files:docker-compose.yml,
label_com_docker_compose_project_working_dir:/secret,
label_com_docker_compose_service:openobserve,
label_com_docker_compose_version:1.29.2,
message:[2023-08-28T15:40:42Z INFO  actix_web::middleware::logger] 192.168.100.100 "POST /api/default/prometheus/api/v1/write HTTP/1.1" 200 20 "56558" "-" "Telegraf/1.19.1 Go/1.16.5" 0.013928,
source_type:docker_logs,
stream:stderr,
timestamp:2023-08-28T15:40:42.283218023Z
} 
```

**Comment by prabhatsharma** [comment] 2023-08-30 23:46
Everything looks to be fine. We have a bug in 0.5.2 the metrics UI where the timestamp was not being picked up. If you refresh the page it should appear. This bug has been fixed in main branch. You could try this dev image where the issue is resolved `public.ecr.aws/zinclabs/openobserve-dev:v0.5.2-e6237f8`

**Comment by userdeveloper98** [comment] 2023-09-03 09:11
Sorry. It turns out to be a misconfiguration on my side.
telegraf was starting with --config-url which was silently overwriting the configuration file.

**Closed** 2023-09-03 09:11 UTC
