### ISSUE TITLE
VRL language commands not working when we create those as a function and associated with a steam

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1421] opened 2023-08-23 17:52 UTC
### Which OpenObserve functionalities are the source of the bug?

streams, functions

### Is this a regression?

Yes

### Description

We are using OpenObserve for our application.
Here when we wanted to perform data enrichment, we are using VRL to perform some actions on specific columns. 

Here what ever we tested in the VRL playground works well. but in the real tool, either we get SQL exception / Internal
server error. Once we removed those statements it works well with the normal data. 

Inside the Openobserve tool's VRL editor none of the single statement is working. If I put any condition and click RUN QUERY, then all the rows and its values are disappearing except time stamp value, which means except timestamp value we are not seeing anything on all the rows even though the VRL statement is correct. But once we removed , we are seeing values on the rows with out doing anything.

What is the issue here, please help. 

Also, in the logs section ,when I click any row, I see data for that column as a JSON. Here, I see the data as akey value pair but both key and values are not surrounded with double quotes ("").

https://raw.githubusercontent.com/openobserve/openobserve/main/screenshots/logs.webp (Actual official documentation)

What we have in our systems is ,

{
  key1 : val 1,
  key2 : val 2,
  key3 : val 3
}

But what I see in the website is,
{
  "key1" : "val 1",
  "key2" : "val 2",
  "key3" : "val 3"

}

Are the VRL statements not working may be Because of this ? I have a doubt like this. 

P.S : We are using FluentD to send data from our production machines to Openobserve platform. 

Please help us. TIA.

Thanks,
R Vaidyanathan

**Comment by prabhatsharma** [comment] 2023-08-23 22:31
Can you provide us more info on what your VRL looks like and some sample data. We need to be able to reproduce the issue in order to help.

**Comment by RVaidhy** [comment] 2023-08-24 07:16
Hi Prabhatsharma,

Thanks for the reply.

https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiIyBQYXJzZSBIVFRQIHN0YXR1cyBjb2RlIGludG8gbG9jYWwgdmFyaWFibGVcbmh0dHBfc3RhdHVzX2NvZGUgPSBwYXJzZV9pbnQhKC5odHRwX3N0YXR1cylcblxuIyBBZGQgc3RhdHVzXG5pZiBodHRwX3N0YXR1c19jb2RlID49IDQwMCAmJiBodHRwX3N0YXR1c19jb2RlIDw9IDQwNSB7XG4gICAgZGVsKC4pXG59XG5pZiAoLnJlcXVlc3RfVVJMICE9IG51bGwpIFxue1xuICAgIGlmIGNvbnRhaW5zKHN0cmluZyEgKC5yZXF1ZXN0X1VSTCksIFwiL2FwaS9zeXN0ZW0vaGVhcnRiZWF0XCIpIHtcbiAgICAgICAgZGVsKC4pXG4gICAgfSBlbHNlIHtcbiAgICBcbiAgICAgICAgLnJlcV91cmxfc3BsaXQsZXJyb3IxPXNwbGl0KC5yZXF1ZXN0X1VSTCwgXCIvXCIpXG4gICAgICAgIC5tYWluID0gLnJlcV91cmxfc3BsaXRbMV1cbiAgICAgICAgLm1haW5fc3BsaXQsZXJyb3IyPXNwbGl0KC5tYWluLCBcIi1cIilcbiAgICAgICAgLnZhbDE9Lm1haW5fc3BsaXRbMF1cbiAgICAgICAgLnZhbDI9Lm1haW5fc3BsaXRbMl1cblxuICAgICAgICBkZWwoLnJlcV91cmxfc3BsaXQpXG4gICAgICAgIGRlbCgubWFpbl9zcGxpdClcblxuICAgIH1cbn0iLCJldmVudCI6eyJ0aW1lc3RhbXAiOiIyMDIzLTA4LTIzVDEwOjQ5OjU5LjQwOVRaIiwiaWQiOiIzMnFxamhhc2QzNHEzNG4iLCJ1c2VybmFtZSI6ImFub255bW91cyIsInJlcXVlc3RfbWV0aG9kIjoiR0VUIiwicmVxdWVzdF9VUkwiOiIvQ09ERS1HRU5FUklDLVRFU1QvYXBwbGljYXRpb24tMS5sb2cuanNvbiIsImFnZW50IjoiSmF2YSIsImh0dHBfc3RhdHVzIjoiMjIwIn0sImlzX2pzb25sIjpmYWxzZSwiZXJyb3IiOm51bGx9


Please look at the sample event and the VRL that we have created. As expected it produces the result. 

The FluentD agent will push the data from our EC2 server and it will be similar to the input event that I have used for this process. Please help us. 


Thanks,
R Vaidhy

**Comment by RVaidhy** [comment] 2023-08-24 07:25
when we try any sample code inside the VRL editor, I receive the following error "Error: Search SQL execute error.
"

**Comment by RVaidhy** [comment] 2023-08-24 11:47
Additionally , if I execute any if condition code for example I if run the below code, I get " Error: Search SQL execute error".

What I tried inside the VRL,

if (.request_user_aget == null) {
    .opetations="SYSTEMS CALL"

}

Even this statement fails with the SQL execute error.

**Comment by prabhatsharma** [comment] 2023-08-25 00:19
this is a bug. We will take it up.

**Comment by oasisk** [comment] 2023-08-29 11:40
@RVaidhy can you try below :

if (.request_user_aget == null) {
.opetations="SYSTEMS CALL"
}
**.** 

Make sure you have **.** in end which returns the modified record , let us know if it fails

**Comment by RVaidhy** [comment] 2023-08-29 11:54
Hi Oasisk,

Nice to hear from you and thanks for letting us know. Let me test and update you in short.

**Comment by RVaidhy** [comment] 2023-08-30 11:50
Hi Oasisk,

We are good with the solution provided. Thanks so much. I am closing this ticket now.

**Comment by hengfeiyang** [comment] 2023-08-30 12:31
@oasisk We should allow the user input function like VRL playground, the last `.` should be optional because many users test it in vrl playground and then copy it to OpenObserve.

**Comment by oasisk** [comment] 2023-09-19 05:10
added . at the end the function, closing

**Closed by oasisk** 2023-09-19 05:10 UTC
Labels: enhancement, testing
