### ISSUE TITLE
Geolocation identification using maxmind Geolite2 DB

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#619] opened 2023-04-24 02:41 UTC
### Which ZincObserve functionalities are relevant/related to the feature request?

functions

### Description

It is helpful in many scenarios to understand from what physical location the requests are generated. This is especially true when it comes to security logs.

### Proposed solution

Maxmind provides Geolite2 database of IP address to location mapping under `Creative Commons` license. ZO should be able to use this to map IP addresses to locations. VRL functions can use [lookup tables](https://vector.dev/docs/reference/vrl/functions/#find_enrichment_table_records) to enrich data. We should be able to pass the mapping files to VRL so it can help map ip->location during query or ingestion.

[Maxmind database is directly supported by vector](https://vector.dev/docs/reference/configuration/global-options/#enrichment_tables)

### Alternatives considered

None

**Comment by prabhatsharma** [comment] 2023-07-10 15:12
Some sample files that can be used for reference
1. https://zinc-public-data.s3.us-west-2.amazonaws.com/geoip/sample/logs_with_geoip.zip
2. https://zinc-public-data.s3.us-west-2.amazonaws.com/geoip/sample/geoip.zip

**Comment by oasisk** [comment] 2023-12-25 10:39
closing as duplicate of https://github.com/openobserve/openobserve/issues/1138

**Closed** 2023-12-25 10:39 UTC
