### ISSUE TITLE
"include term" button in SQL mode changes case of previous filters

### ISSUE THREAD

**Issue by laurst** [openobserve/openobserve#3898] opened 2024-07-03 16:02 UTC
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

In log search, and in SQL mode, if I am filtering in my query, like so for instance:

```
select * from "stream" where host_name = 'FOObar1' order by _timestamp desc
```

and now I click on the "include term" (or the "exclude term" button) in the search results, it will correctly add the include term. However it will turn all the previous filters to lowercase, like so:

```
select * from "stream" where host_name = 'foobar1' AND favorite_color = 'Blue' order by _timestamp desc
```

And now my search does not work as intended anymore.

Now if I click on another "include term", `Blue` will turn into `blue`.

This does not happen in non-SQL mode as far as I can see

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.7
611f2e1c29df33a2df8e3be8a726889b07485284
2024-06-12T14:11:18Z
```

### Anything else?

It was also happening in v0.10.6, I don't know about previous versions.

**Comment by bjp232004** [comment] 2024-08-06 09:27
Unable to reproduce the issue now. It appears to have been fixed in the PR below: https://github.com/openobserve/openobserve/pull/3766

**Closed** 2024-12-13 14:09 UTC
Labels: testing, ☢️ Bug
