### ISSUE TITLE
Dashboard Pie chart overlaps

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#4431] opened 2024-09-02 07:18 UTC
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

<img width="937" alt="Screenshot 2024-09-02 at 10 44 18 AM" src="https://github.com/user-attachments/assets/c4844a08-f0fe-4572-871f-0629983150db">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.11.0-rc3
ae4b30b3994f30c11095d06667eb70ffee5b5664
2024-09-02T04:32:53Z
```

**Comment by gaby** [comment] 2024-09-02 10:21
@neha00290 @ktx-abhay Duplicate of https://github.com/openobserve/openobserve/issues/4256

I reported this a month ago. Issue has been there since the very beginning, depends how you arrange your chart.

**Closed** 2024-12-02 05:54 UTC
Labels: testing, ☢️ Bug
