### ISSUE TITLE
Changing root password cause authentication to hang after process restart

### ISSUE THREAD

**Issue by Var-b** [openobserve/openobserve#4174] opened 2024-08-10 17:32 UTC
### Which OpenObserve functionalities are the source of the bug?

login

### Is this a regression?

Yes

## Description:
After changing the root password using the IAM menu, if you restart the OpenObserve process (via service, or killing the process and relaunching it), the login process will hang when attempting to login with the correct root credentials.

## Reproduction:
1. Install OpenObserve by downloading the binary (usage of the install script for example)
2. Start OpenObserve by specifying the defualt root username and password (via command line argument or env file for service)
3. Login to OpenObserve, go to IAM menu, change root password
4. Logout
5. Login with new root password (Should work ok)
6. (Optional) logout
7. Restart OpenObserve (kill the process and relaunch binary, without the env variable, or restart the service after removing the env variable file from the service options)
8. (Optional) Attempt to login with old root password -> Should get error wrong credentials
9. (May Happen) Attempt to login with new root account login and password -> Login process will succeed, but you will be logged out immediately
10. Attempt to login with new root account login and password -> Login process will hang indefinitly

## Expected Outcome
Login successfully with new root account password

## Work Around
Specify the default root password when starting the process to be able to log in again (with the provided password in the command line/env file)

## Comment
Based from previous issues, there were somewhat similar bugs in the past that had been fixed, thus I am marking this as regression, but happy to change if requested :)

### Please provide the exception or error you saw

```true
Login hangs with the login button animation never ending, no error message.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.9-rc3
Commit Hash: 42359ddc5bed64a2173ea59f6070212a8c33b2a4
Build Date: 2024-07-30T10:18:56Z
OS: Linux x64
```

**Comment by uddhavdave** [comment] 2024-08-11 13:57
This is due to issue #4115 , where the role change of user would cause the root to loose access to default. Since this has been fixed, can you try using the main branch?

**Comment by uddhavdave** [comment] 2024-08-13 03:11
Closing this since its not reproducible on latest branch. Solution is to use release versions higher than v0.10.9-rc3. Please reopen if this is still an issue.

**Closed by uddhavdave** 2024-08-13 03:11 UTC
Labels: ☢️ Bug
