### ISSUE TITLE
Alert auto creates a "triggers" stream  within the "_meta"  org

### ISSUE THREAD

**Issue by eddyyuen** [openobserve/openobserve#3626] opened 2024-05-30 03:22 UTC
### Which OpenObserve functionalities are the source of the bug?

streams, alerts

### Is this a regression?

Yes

### Description

After openobserve upgrade to V0.10.4
I found Alert auto creates a ""triggers" stream  within the "_meta"   organization。
How can i close it ?

![4e3a135baed65747011da137866f6cd](https://github.com/openobserve/openobserve/assets/9354119/be9c8447-3b32-4807-aa16-e1622b7b8cde)

And my docker command :
docker run -v /data:/data -e ZO_DATA_DIR="/data" -p 4080:5080 \
-e ZO_ROOT_USER_EMAIL=... -e ZO_ROOT_USER_PASSWORD=... \
-e ZO_LOCAL_MODE_STORAGE=s3  -e ZO_S3_SERVER_URL=... \
-e ZO_S3_REGION_NAME=...  -e ZO_S3_ACCESS_KEY=... \
-e ZO_S3_SECRET_KEY=... -e ZO_S3_BUCKET_NAME=...\
-e ZO_COMPACT_DATA_RETENTION_DAYS=31 \
-e ZO_S3_FEATURE_FORCE_PATH_STYLE=true \
--restart=always -d --name zincobserve openobserve/openobserve:v0.10.4

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.4  
15f9788a6e6e7fef004bb227dedf46dfff3402ec  
2024-04-29T03:29:00Z
```

**Comment by Subhra264** [comment] 2024-05-30 06:45
Hello @eddyyuen, this was fixed by #3370 and was part of the release [v0.10.5](https://github.com/openobserve/openobserve/releases/tag/v0.10.5). Please upgrade to `v0.10.5` and confirm if the issue is fixed.

**Closed** 2024-05-30 15:11 UTC
Labels: ☢️ Bug
