### ISSUE TITLE
Add ability to resize a column in the log search

### ISSUE THREAD

**Issue by unixfox** [openobserve/openobserve#971] opened 2023-06-15 22:19 UTC
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

Sometimes I don't want the full text value of a column in a log search when comparing multiple logs lines.

### Proposed solution

Adding the ability to resize the size of a column would be great, it would make comparing multiple logs line much easier and especially when there are many columns.

The same functionality exist in Kibana: https://www.elastic.co/guide/en/kibana/current/document-explorer.html#document-explorer-columns

### Alternatives considered

N/A

**Comment by prabhatsharma** [comment] 2023-06-16 00:04
duplicate of https://github.com/openobserve/openobserve/issues/573

**Closed by prabhatsharma** 2023-06-16 00:04 UTC
