### ISSUE TITLE
RUM & Session Replay

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#1402] opened 2023-08-19 05:56 UTC
### Description

RUM & Session Replay integration.

### Proposed solution

[Click here](https://github.com/DataDog/browser-sdk)

### Alternatives considered

No

**Comment by prabhatsharma** [comment] 2023-08-21 22:51
duplicate of https://github.com/openobserve/openobserve/issues/1110

**Closed by prabhatsharma** 2023-08-21 22:51 UTC
