### ISSUE TITLE
Could you pls remove video on dashboard

### ISSUE THREAD

**Issue by thomasdba** [openobserve/openobserve#1480] opened 2023-09-11 03:20 UTC
No on will click and watch video through that , in prod env , it looks more ridiculous and not serious .
I'm satisfied about most of functions except for this .
thanks !

**Comment by prabhatsharma** [comment] 2023-09-11 04:55
closing as duplicate of https://github.com/openobserve/openobserve/issues/957

**Closed by prabhatsharma** 2023-09-11 04:55 UTC
