### ISSUE TITLE
Auth per stream

### ISSUE THREAD

**Issue by mr-karan** [openobserve/openobserve#1508] opened 2023-09-14 08:20 UTC
### Which OpenObserve functionalities are relevant/related to the feature request?

User Management

### Description

I find the concept of Organisation a bit broad. In a team of developers working on multple projects, I think the ability to restrict certain teams to specific streams only. They all come under a single org, but within that, they should have restricted access to the streams inside each org.

### Proposed solution

We can have the ability to set a specifc role/group attribute on the stream and assign that group to the user in the User Management panel.

- There can be a "Add Group" feature, multiple users can be added. 
- On the stream management page, we can set group(s) who have access to the stream
- The API handlers can check at the router/query level and decide whether to proceed with the request or not. 

### Alternatives considered

Creating multiple org for multiple streams, something that doesn't scale very well if there are too many orgs. Each org essentially ends up having a single stream because of this. 

And since creating orgs [isn't an OSS offering](https://openobserve.ai/docs/user-guide/organizations/), essentially there's no way to do ^.

**Comment by prabhatsharma** [comment] 2023-09-14 09:40
duplicate of https://github.com/openobserve/openobserve/issues/304 . You could create orgs in Open source version. The process is a bit convoluted and we will make it better. Follow - https://github.com/openobserve/openobserve/discussions/985

**Closed by prabhatsharma** 2023-09-14 09:40 UTC
